### ISSUE TITLE
Fix the CfP generated text

### ISSUE THREAD

**Issue by jeremiewcz** [hackstub/rmll18-osem#2]
Change : "You can submit proposals for Workshops, Workshops, Workshops, Workshops, Conferences, Conferences, Chatrooms, Chatrooms, Chatrooms, Chatrooms, Debates ("table rondes")s, Creations, and Others. Proposals should fit in one of the 6 tracks: Digital education: building captivity or new empowerment, Free Software Foundation Europe, [theme] Culture and Art, [theme] Initiation, [theme] Society, and [theme] Tech. The submission period is open March 12 - April 15, 2018. You have 33 days left! "
To : "You can submit proposals for workshops, conferences, chatrooms, debates, creations and others. Proposals should fit in one of the 6 tracks and themes: Digital education: building captivity or new empowerment, Free Software Foundation Europe, [theme] Culture and Art, [theme] Initiation, [theme] Society, and [theme] Tech. The submission period is open March 12 - April 15, 2018. You have 33 days left! "

**Comment by sandhose** [comment]
Fixed by 1d54c75
